In [1]:
    import numpy as np
    arr=np.array([1,2,3,4,5])
    print(arr)

[1 2 3 4 5]


In [2]:
print(type(arr))

<class 'numpy.ndarray'>


In [3]:
# create array using tuple
tup_arr=np.array((1,2,3,4,5))
print(tup_arr)
print(type(tup_arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
# dimensions
print("0 dim")
arr=np.array(420)#0 D
print(arr)
print(arr.ndim)
print("1 Dim")
arr=np.array([11,12,13])# 1 D
print(arr)
print(arr.ndim)
print("2 Dim")
arr=np.array([[1,2,3,4,5],[6,7,8,9,0]]) #2 D
print(arr)
print(arr.ndim)
print("3 dim")
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]]) #3D
print(arr)
print(arr.ndim)
print("5 dim")
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print(arr.ndim)

0 dim
420
0
1 Dim
[11 12 13]
1
2 Dim
[[1 2 3 4 5]
 [6 7 8 9 0]]
2
3 dim
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
5 dim
[[[[[1 2 3 4 5]]]]]
5


In [11]:
#Array Indexing
import numpy as np
one=np.array([1,2,3,4,5])
print(one)
print("*******************************************************")
print(one[0])#returns first elements
print("*******************************************************")
print(one[1])#returns second elements
print("*******************************************************")
print(one[2]+one[3])#returns  sum of third and fourth elements
print("*******************************************************")
print(one[:4])# returns the elements upto 4th position
print("*******************************************************")
print(one[2:])#returns from the 3rd elements


[1 2 3 4 5]
1
2
7
[1 2 3 4]
[3 4 5]


In [18]:
import numpy as np
two=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(two)
print("*********")
print(two[1])#returns second row
print(two[0])#returns first row
print(two[0,1])#returns first rows and second columns
print(two[1,1])#returns second rows and second columns
print(two[1,0])#returns second rows first columns
print(two[0,0])#returns first rows first columns
print(two[1,4])#returns second rows fourth columns
print(two[0,4])#returns first rows fourth columns 

[[1 2 3 4 5]
 [6 7 8 9 0]]
*********
[6 7 8 9 0]
[1 2 3 4 5]
2
7
6
1
0
5


In [27]:
three=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]],[["ram","shyam","vishnu"],["luv","Kush","Ganesh"],["sita","radha","laxmi"]]])
print(three)
print("*******************************************************")
print(three[0])
print("*******************************************************")
print(three[1])
print("*******************************************************")
print(three[2])
print("*******************************************************")
print(three[1,2])
print("*******************************************************")
print(three[2,1])
print("*******************************************************")
print(three[0,2])
print("*******************************************************")
print(three[2,0])
print("*******************************************************")
print(three[2,1])
print("*******************************************************")
print(three[1,2])
print("*******************************************************")
print(three[2,2,0])
print("*******************************************************")
print(three[1,0,2])
print("*******************************************************")

[[['1' '2' '3']
  ['4' '5' '6']
  ['7' '8' '9']]

 [['9' '8' '7']
  ['6' '5' '4']
  ['3' '2' '1']]

 [['ram' 'shyam' 'vishnu']
  ['luv' 'Kush' 'Ganesh']
  ['sita' 'radha' 'laxmi']]]
*******************************************************
[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]
*******************************************************
[['9' '8' '7']
 ['6' '5' '4']
 ['3' '2' '1']]
*******************************************************
[['ram' 'shyam' 'vishnu']
 ['luv' 'Kush' 'Ganesh']
 ['sita' 'radha' 'laxmi']]
*******************************************************
['3' '2' '1']
*******************************************************
['luv' 'Kush' 'Ganesh']
*******************************************************
['7' '8' '9']
*******************************************************
['ram' 'shyam' 'vishnu']
*******************************************************
['luv' 'Kush' 'Ganesh']
*******************************************************
['3' '2' '1']
*****************************

In [30]:
print(one[-4])#returns 4th element from right side
print(one[-1])#returns last element
print(two[-1,-2])

2
5
1
9


In [33]:
  # Array slicing
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[1:5])
print(arr[1:8:2])# 1 is for start position and 8 is for end position and 2 is steps
print(arr[2:])
print(arr[:4])
print(arr[::2])# returns every other elements of the entire array
print(arr[-3:-1])

[2 3 4 5]
[2 4 6 8]
[3 4 5 6 7 8]
[1 2 3 4]
[1 3 5 7]
[6 7]


In [39]:
two=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(two)
print(two[1,2:4])
print(two[0,2:4])
print(two[0:2,2])

[[1 2 3 4 5]
 [6 7 8 9 0]]
[8 9]
[3 4]
[3 8]


In [42]:
integer=np.array([1,2,3,4,5])
print(integer.dtype)
string=np.array(["Ram","Shyam","Hari"])
print(string.dtype)
Float=np.array([1.2,2.3,4,.5])
print(Float.dtype)

int64
<U5
float64


In [44]:
#creating value with a defined data type
intstr=np.array([1,2,3,4,5], dtype='S')
print(intstr)
print(intstr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [51]:
strint=np.array([1.2,2.4,3.4,5.3,2.5], dtype='i')
print(strint)
print(strint.dtype)

[1 2 3 5 2]
int32


In [53]:
intostr=strint.astype("S")
print(intostr)
print(intostr.dtype)

[b'1' b'2' b'3' b'5' b'2']
|S11


In [55]:
#copy vs view
arrey=np.array([1,2,3,4,5])
x=arrey.copy() #x creates new array with its own data
arrey[0]=50
print(arrey)
print(x)
y=arrey.view()# Y modifies the data of arrey and store it in original arrey
arrey[0]=70
print(arrey)
print(y)

[50  2  3  4  5]
[1 2 3 4 5]
[70  2  3  4  5]
[70  2  3  4  5]


In [56]:
#checking if the array owns its data by using base attributes
#None results means its doesn't owns its data
print(x.base)
print(y.base)

None
[70  2  3  4  5]


In [58]:
print(arrey.shape)

(5,)


In [59]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [62]:
newarr=arr.reshape(9)
print(newarr)
print(newarr.shape)

[1 2 3 4 5 6 7 8 9]
(9,)


In [63]:
arr=np.array([1,2,3,4,5,6,7,8,9,0,2,4])
ar=arr.reshape(2,3,2)
print(ar)
print(ar.shape)

[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [9 0]
  [2 4]]]
(2, 3, 2)


In [66]:
for x in arr:
    print(x)
    
    
print(arr)

1
2
3
4
5
6
7
8
9
0
2
4
[1 2 3 4 5 6 7 8 9 0 2 4]


In [67]:
arr=np.array([[1,2,3],[3,2,3]])
for x in arr:
    print(x)

[1 2 3]
[3 2 3]


In [68]:
for x in arr:
    for y in x:
        print(y)

1
2
3
3
2
3


In [69]:
for x in np.nditer(arr):
    print(x)

1
2
3
3
2
3


In [71]:
for idx, x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 3
(1, 1) 2
(1, 2) 3


In [5]:
import numpy as np
arr1=np.array([[1,3,4,6],[2,4,6,7]])
arr2=np.array([[9,0,8,7],[5,4,3,6]])
join=np.concatenate((arr1,arr2))
print(join)

[[1 3 4 6]
 [2 4 6 7]
 [9 0 8 7]
 [5 4 3 6]]


In [7]:
axis1=np.concatenate((arr1,arr2),axis=1)
print(axis1)

[[1 3 4 6 9 0 8 7]
 [2 4 6 7 5 4 3 6]]


In [9]:
stack1=np.stack((arr1,arr2),axis=1)
print(stack1)

[[[1 3 4 6]
  [9 0 8 7]]

 [[2 4 6 7]
  [5 4 3 6]]]


In [11]:
stack2=np.stack((arr1,arr2),axis=2)
print(stack2)

[[[1 9]
  [3 0]
  [4 8]
  [6 7]]

 [[2 5]
  [4 4]
  [6 3]
  [7 6]]]


In [12]:
stackrow=np.hstack((arr1,arr2))
print(stackrow)

[[1 3 4 6 9 0 8 7]
 [2 4 6 7 5 4 3 6]]


In [13]:
stackcol=np.vstack((arr2,arr1))
print(stackcol)

[[9 0 8 7]
 [5 4 3 6]
 [1 3 4 6]
 [2 4 6 7]]


In [15]:
arr1=np.array([1,2,3,4,5,6,7,8])
split1=np.array_split(arr1,3)# adjust the number of elements from last array
print(split1)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [16]:
print(split1[0])
print(split1[1])
print(split1[2])

[1 2 3]
[4 5 6]
[7 8]


In [17]:
arr2=np.array([[1,2,3],[2,3,4],[3,4,5]])
print(arr2)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [19]:
print(arr2.ndim)

2


In [21]:
split2=np.array_split(arr2,3)
print(split2)

[array([[1, 2, 3]]), array([[2, 3, 4]]), array([[3, 4, 5]])]


In [32]:
split3=np.array_split(arr2,4)
print(split3)

[array([[1, 2, 3]]), array([[2, 3, 4]]), array([[3, 4, 5]]), array([], shape=(0, 3), dtype=int64)]


In [35]:
splitrow=np.hsplit(arr2,3)
print(splitrow)
print("****************************************************************")
splitcol=np.vsplit(arr2,3)
print(splitcol)
print("********************************************************************")
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]]])
splitdim=np.dsplit(arr3,3)
print(splitdim)
print("******************************************************************")

[array([[1],
       [2],
       [3]]), array([[2],
       [3],
       [4]]), array([[3],
       [4],
       [5]])]
****************************************************************
[array([[1, 2, 3]]), array([[2, 3, 4]]), array([[3, 4, 5]])]
********************************************************************
[array([[[1],
        [4],
        [7]],

       [[9],
        [6],
        [3]]]), array([[[2],
        [5],
        [8]],

       [[8],
        [5],
        [2]]]), array([[[3],
        [6],
        [9]],

       [[7],
        [4],
        [1]]])]
******************************************************************


In [6]:
#search in array using where
import numpy as np
arr=np.array([1,2,3,4,5,2,2,9,])
search=np.where(arr==4)# returns the index of 4
sear=np.where(arr==2)# returns the indexes of 2
odd=np.where(arr%2==1)
even=np.where(arr%2==0)
print(search)
print(sear)
print(odd)
print(even)



(array([3]),)
(array([1, 5, 6]),)
(array([0, 2, 4, 7]),)
(array([1, 3, 5, 6]),)


In [11]:
# search using searchsorted
arr2=np.array([1,5,3,9,8])
left=np.searchsorted(arr2,9)# returns the indexes of 9 by sorted by left side
right=np.searchsorted(arr2,9)#returns the indexes sorted by right side
print(left)
print(right)
multiple=np.searchsorted(arr2,[1,3,8])
print(multiple)


5
5
[0 1 3]


In [16]:
#array sorting
arr1=np.array([1,4,3,2,6,5])
x=np.sort(arr1)# this returns a copy of array in sorted form
print(x)
print(arr1)
arr2=np.array([True, False, True,False,False])
print(np.sort(arr2))
twoD=np.array([[1,4,2,3],[7,5,6,8]])
print(np.sort(twoD))

[1 2 3 4 5 6]
[1 4 3 2 6 5]
[False False False  True  True]
[[1 2 3 4]
 [5 6 7 8]]


In [20]:
arr=np.array([1,3,5,7])
filt_arr=np.array([True,False,False,True])
newarr=arr[filt_arr]
print(newarr)

[1 7]


In [28]:
arr2=np.array([1,2,3,4,5,6,7,8,9])
filt_arr=[]
for element in arr2:
    if element%2==0:
        filt_arr.append(True)
    else:
        filt_arr.append(False)
newarr=arr2[filt_arr]
print(newarr)


[2 4 6 8]


In [29]:
arr3=np.array([32,43,36,35])
empty=[]
for element in arr3:
    if element>35:
        empty.append(True)
    else:
        empty.append(False)
newarr2=arr3[empty]
print(newarr2)

[43 36]
